In [59]:
import numpy as np
pi = np.pi

def LUDECMP(A):
    N = A.shape[0]
    indx = [0] * N
    vv = [0] * N
    TINY = 1.0E-20 
    d = 1.0 
    for i in range(N):
        big = 0.0
        for j in range(N): 
            temp = abs(A[i,j])
            if temp > big:
                big = temp
        if big == 0.0:
            print("Singular Matrix")
        vv[i] = 1.0/big
    for j in range(N):
        for i in range(j):
            asum = A[i,j]
            for k in range(i):
                asum = asum - A[i,k]*A[k,j]
            A[i,j] = asum
        big = 0.0
        for i in range(j,N):
            asum = A[i,j]
            for k in range(j):
                asum = asum - A[i,k]*A[k,j]
            A[i,j] = asum
            dum = vv[i]*abs(A[i,j])
            if dum >= big:
                big = dum
                imax = i
        if j != imax:
            for k in range(N):
                dum = A[imax,k]
                A[imax,k] = A[j,k]
                A[j,k] = dum
            d = -d 
            vv[imax] = vv[j]
        indx[j] = imax
        if A[j,j] == 0.0:
            A[j,j] = TINY
        if j != (N-1):
            dum = 1.0/A[j,j]
            for i in range(j+1,N):
                A[i,j] = A[i,j]*dum
    
    return indx, d, A


def LUBKSB(A, b, indx):
    N = A.shape[0]
    ii = -1
    for i in range(N):
        ip = indx[i]
        asum = b[ip]
        b[ip] = b[i]
        if ii != -1:
            for j in range(ii, i):
                asum = asum - A[i,j]*b[j]
        elif asum != 0.:
            ii = i
        b[i] = asum
    for i in range(N-1,-1,-1):
        asum = b[i]
        for j in range(i+1,N):
            asum -= A[i,j]*b[j]
        b[i] = asum/A[i,i]
    
    return b

In [60]:
# TESTING CASE 1

A = np.matrix([[1., 2., -1.],[6., -5., 4.], [-9., 8., -7.]])
print("A =")
print(A)
indx, d, LU = LUDECMP(A)     
b = [2*pi, 5*pi, -8*pi]
print("")
print("b = ")
print(b)
x = LUBKSB(LU, b, indx)
print("")
print("x = ")
print(x)

A =
[[ 1.  2. -1.]
 [ 6. -5.  4.]
 [-9.  8. -7.]]

b = 
[6.283185307179586, 15.707963267948966, -25.132741228718345]

x = 
[3.141592653589794, 3.1415926535897927, 3.1415926535897922]


In [61]:
# TESTING CASE 2

A = np.matrix([[pi, 3*pi, 2*pi],[0., 1., -2./3.], [-pi, -3*pi, 2*pi]])
print("A =")
print(A)
indx, d, LU = LUDECMP(A)     
b = [3., 0., -1.]
print("")
print("b = ")
print(b)
x = LUBKSB(LU, b, indx)
print("")
print("x = ")
print(x)

A =
[[ 3.14159265  9.42477796  6.28318531]
 [ 0.          1.         -0.66666667]
 [-3.14159265 -9.42477796  6.28318531]]

b = 
[3.0, 0.0, -1.0]

x = 
[0.3183098861837907, 0.1061032953945969, 0.15915494309189535]
